

# This file was *autogenerated* from the file testi/primer.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_25 = Integer(25)
from sage.all import *
load("graph_tools.sage")
load('prediction_model.sage')
G = Graph([(_sage_const_0 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_0 )])  # C3
print("alpha_od(G) =", alpha_od_ilp_correct(G))
print("alpha(G) =", G.independent_set(value_only=True))




# Kvadrat grafa - vozlišča povezana, če so v razdalji <= 2
G_squared = graph_power(G, _sage_const_2 )
print("alpha(G^2) =", G_squared.independent_set(value_only=True))

H = Graph([(_sage_const_0 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ),(_sage_const_3 ,_sage_const_0 )])  # C4
print("alpha_od(H) =", alpha_od_ilp_correct(H))
print("alpha(H) =", H.independent_set(value_only=True))




# Kvadrat C4
H_squared = graph_power(H, _sage_const_2 )
print("alpha(H^2) =", H_squared.independent_set(value_only=True))
print("Povezave v H^2:", H_squared.edges(labels=False))
print("alpha^2(G) =", graph_power(G, _sage_const_2 ).independent_set(value_only=True))

predict_alfas(G)
predict_alfas(H)
print(G.diameter())  # Premer grafa G


F = graphs.CompleteGraph(_sage_const_25 )
predict_alfas(F)

