

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
from sage.all import *
import csv
load("graph_tools.sage")

# Funkcija za pretvorbo grafa v string povezav
def graph_to_edge_string(G):
    """Pretvori graf v string povezav v formatu '[(0,1),(1,2),...]'"""
    edges = [(min(u,v), max(u,v)) for u,v in G.edges(labels=False)]
    edges.sort()
    return str(edges)

# Funkcija za shranjevanje grafov v CSV
def save_graphs_to_csv(graphs, filename='data/grafi_oblika.csv'):
    """Shrani grafe v CSV format z headerjem 'graf,povezave'"""
    # Preberi obstoječe grafe
    existing_graphs = {}
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                existing_graphs[row['povezave']] = row['graf']
    except FileNotFoundError:
        pass
    
    # Dodaj nove grafe
    with open(filename, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['graf', 'povezave'])
        
        # Najprej zapiši obstoječe grafe
        for edge_string, graf_ime in existing_graphs.items():
            writer.writerow([graf_ime, edge_string])
        
        # Dodaj nove grafe (če še ne obstajajo)
        for G_data in graphs:
            if isinstance(G_data, tuple):
                G, ime, druzina = G_data
            else:
                G, ime, druzina = G_data, f"G{len(existing_graphs)}", "neznan"
            
            edge_string = graph_to_edge_string(G)
            if edge_string not in existing_graphs:
                writer.writerow([ime, edge_string])
                existing_graphs[edge_string] = ime
    
    return existing_graphs

# Funkcija za preverjanje lastnosti in shranjevanje
def analyze_and_save_graphs(graphs, properties_file='data/grafi.csv', graphs_file='data/grafi_oblika.csv'):
    """Preveri lastnosti grafov in shrani rezultate v CSV datoteke"""
    
    # Shrani grafe in pridobi mapping (povezave -> ime)
    graph_mapping = save_graphs_to_csv(graphs, graphs_file)
    
    # Preberi obstoječe lastnosti
    existing_properties = {}
    fieldnames_set = set(['graf', 'druzina'])
    try:
        with open(properties_file, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                existing_properties[row['graf']] = row
                fieldnames_set.update(row.keys())
    except FileNotFoundError:
        pass
    
    # Preberi VSE grafe iz grafi_oblika.csv za računanje manjkajočih lastnosti
    all_graphs = {}
    try:
        with open(graphs_file, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                all_graphs[row['graf']] = row['povezave']
    except FileNotFoundError:
        pass
    
    # Pripravi podatke za grafi.csv - vključi VSE grafe iz graph_mapping
    results_dict = {}
    
    # Najprej dodaj vse obstoječe lastnosti
    for graf_ime, props in existing_properties.items():
        results_dict[graf_ime] = props.copy()
    
    # Ustvari slovar grafov za hitrejši dostop
    graphs_dict = {}
    for G_data in graphs:
        if isinstance(G_data, tuple):
            G, ime, druzina = G_data
        else:
            G, ime, druzina = G_data, "", "neznan"
        graphs_dict[ime] = (G, druzina)
    
    # Obdelaj VSE grafe iz grafi_oblika.csv
    for graf_ime, edge_string in all_graphs.items():
        # Če graf še ni v results_dict, dodaj osnovne podatke
        if graf_ime not in results_dict:
            results_dict[graf_ime] = {'graf': graf_ime, 'druzina': ''}
        
        # Pridobi graf objekt
        G = None
        druzina = None
        if graf_ime in graphs_dict:
            G, druzina = graphs_dict[graf_ime]
            # Posodobi družino SAMO če je podana in obstoječa je prazna
            if druzina and druzina != "neznan":
                if not results_dict[graf_ime].get('druzina') or results_dict[graf_ime]['druzina'] == "neznan":
                    results_dict[graf_ime]['druzina'] = druzina
        else:
            # Rekonstruiraj graf iz edge_string
            edges = eval(edge_string)
            G = Graph(edges)
        
        # Izračunaj lastnosti za VSE grafe, kjer manjkajo
        if 'alpha' not in results_dict[graf_ime] or not results_dict[graf_ime].get('alpha'):
            results_dict[graf_ime]['alpha'] = G.independent_set(value_only=True)
        if 'alpha_od' not in results_dict[graf_ime] or not results_dict[graf_ime].get('alpha_od'):
            results_dict[graf_ime]['alpha_od'] = alpha_od(G)
        if 'alpha^2' not in results_dict[graf_ime] or not results_dict[graf_ime].get('alpha^2'):
            results_dict[graf_ime]['alpha^2'] = graph_power(G, _sage_const_2 ).independent_set(value_only=True)

        fieldnames_set.update(results_dict[graf_ime].keys())
    
    # Pretvori dictionary v seznam
    results = list(results_dict.values())
    
    # Shrani lastnosti v grafi.csv
    if results:
        fieldnames = sorted(fieldnames_set)
        # Zagotovi, da sta graf in druzina na začetku
        priority_fields = ['graf', 'druzina']
        fieldnames = priority_fields + [f for f in fieldnames if f not in priority_fields]
        
        with open(properties_file, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(results)



# Primer uporabe:
graphs = generate_graph_family(graphs.CompleteGraph, "K", "polni", _sage_const_1 , _sage_const_10 )


analyze_and_save_graphs(graphs)

